name = "PhaseFromInterferograms"
uuid = "0563bf26-974b-441d-8ac2-0f187e765f6c"
authors = ["Oleg Soloviev"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
